### ISSUE TITLE
Cannot generate a tree of single leaf

### ISSUE THREAD

**Issue by mikiquantum** [centrifuge/precise-proofs#59]
```
func Test_EmptyLeaveFails(t *testing.T) {
	salts := Salts{}
	doc := &documentspb.SimpleEntries{}
	doctree := NewDocumentTree(TreeOptions{Hash: sha256Hash, Salts: &salts})
	err := doctree.AddLeavesFromDocument(doc)
	assert.Nil(t, err)
	err = doctree.Generate()
	assert.Nil(t, err)
}
```
Document used: https://github.com/centrifuge/precise-proofs/blob/4b2df6595f0b4e119ce20df5d9f1bac358c8589e/examples/documents/example.proto#L65

Fails at generation time with (`doctree.Generate()`): 
```
=== RUN   Test_EmptyLeaveFails
--- FAIL: Test_EmptyLeaveFails (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 19 [running]:
testing.tRunner.func1(0xc00010a200)
	/usr/local/Cellar/go/1.11.1/libexec/src/testing/testing.go:792 +0x387
panic(0x14161c0, 0x17e9ce0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:513 +0x1b9
github.com/centrifuge/precise-proofs/vendor/github.com/xsleonard/go-merkle.(*Tree).generateNodeLevel(0xc00014de78, 0xc000164540, 0x1, 0x1, 0xc000164540, 0x0, 0x0, 0x1503bc0, 0xc0000c6400, 0x0, ...)
	/Users/miguelhervas/centrifuge/boilerplate/src/github.com/centrifuge/precise-proofs/vendor/github.com/xsleonard/go-merkle/merkle.go:178 +0x32d
github.com/centrifuge/precise-proofs/vendor/github.com/xsleonard/go-merkle.(*Tree).Generate(0xc00014de78, 0xc0000bd0e0, 0x1, 0x1, 0x1503bc0, 0xc0000c6400, 0x190d6c0, 0x0)
	/Users/miguelhervas/centrifuge/boilerplate/src/github.com/centrifuge/precise-proofs/vendor/github.com/xsleonard/go-merkle/merkle.go:137 +0x3ec
github.com/centrifuge/precise-proofs/proofs.(*DocumentTree).Generate(0xc00014de78, 0xc00010a200, 0x0)
	/Users/miguelhervas/centrifuge/boilerplate/src/github.com/centrifuge/precise-proofs/proofs/tree.go:366 +0x1e5
github.com/centrifuge/precise-proofs/proofs.Test_EmptyLeaveFails(0xc00010a200)
	/Users/miguelhervas/centrifuge/boilerplate/src/github.com/centrifuge/precise-proofs/proofs/tree_test.go:1536 +0x190
testing.tRunner(0xc00010a200, 0x14a4858)
	/usr/local/Cellar/go/1.11.1/libexec/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/Cellar/go/1.11.1/libexec/src/testing/testing.go:878 +0x353
```

Expected behavior:

Be able to create a tree of a single leaf.

**Comment by mikiquantum** [comment]
@lucasvo Fix https://github.com/mikiquantum/go-merkle/commit/9a8290da4794e86e430f8e9494b9c11627bace21
The current go-merkle implementation does not support a single leaf tree due to the line removed in the above commit.
There are two approaches to fix this:
- Tree height for a 1 node tree is 1 (root node)
- Tree height for a 1 node tree is 2 (root node + leaf). In which case we need to change the `calculateNodeCount` function to return 2 nodes when len(leaves) is 1.

I incline for the first option as shown in the commit.

**Comment by lucasvo** [comment]
@mikiquantum I think the first option is the better solution. It doesn't make sense to hash a hash again to get a root.

**Comment by mikiquantum** [comment]
Fixed by: https://github.com/centrifuge/precise-proofs/pull/61
